package com.demo.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("class", "id", Class.class);
		arp.addMapping("class_detail", "id", ClassDetail.class);
		arp.addMapping("inspic", "id", Inspic.class);
		arp.addMapping("instrument", "id", Instrument.class);
		arp.addMapping("picture_ins", "id", PictureIns.class);
		arp.addMapping("picture_user", "id", PictureUser.class);
		arp.addMapping("product", "id", Product.class);
		arp.addMapping("teacher", "id", Teacher.class);
		arp.addMapping("users", "id", Users.class);
	}
}

