package com.demo.common.model;

import com.demo.common.model.base.BaseInstrument;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Instrument extends BaseInstrument<Instrument> {
	public static final Instrument dao = new Instrument();
}
