package com.demo.common.model;

import com.demo.common.model.base.BasePictureIns;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureIns extends BasePictureIns<PictureIns> {
	public static final PictureIns dao = new PictureIns();
}
