package com.demo.common.model;

import com.demo.common.model.base.BasePictureUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class PictureUser extends BasePictureUser<PictureUser> {
	public static final PictureUser dao = new PictureUser();
}
